language: node_js
node_js:
  - 9
  - 8
script: npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true